version: "3"

services:
  nginx:
    networks: 
      - neurallabsapi
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports: 
      - "8000:80"
      - "443:443"
    volumes: 
      - ./app/neurallabs.web/src:/var/www/html
      - ./app/neurallabs.web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php 
      - mysql
      - flask

  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: neurallabs.ml.flask
    ports: 
      - "5000:5000"
    networks: 
      - neurallabsapi

  php:
    build:
      context: ./app/neurallabs.web
      dockerfile: Dockerfile
      args:
        user: ikky
        uid: 1001
    container_name: php
    ports: 
      - "9000:9000"
    working_dir: /var/www/html
    volumes: 
      - ./app/neurallabs.web/src:/var/www/html
      - ./app/neurallabs.web/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment: 
      SERVICE_NAME: php-labs-dev
      SERVICE_TAGS: php
    networks:
      - neurallabsapi

  mysql:
    image: mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: neurallabs_tb_api
      MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: mysql-labs-dev
      SERVICE_NAME: mysql
    volumes:
      - ./app/neurallabs.web/mysql/my.cnf:/etc/mysql/my.cnf 
      - ./app/neurallabs.web/mysql-data:/var/lib/mysql
    networks: 
      - neurallabsapi

#Volumes - Volume accessible across all services
volumes: 
  mysql-data:
    driver: local


networks:
  neurallabsapi:
    driver: bridge
